draw_config:
  dark_mode: true
parse_config:
  trans_legend:
    t: ''
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: C
    right_ctrl: C
    left_shift: S
    right_shift: S
    left_alt: M
    right_alt: M
    left_gui: s
    right_gui: s
    keycode_combiner: '{mods}-{key}'
    mod_combiner: '{mod_1}-{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    'ENTER': '⏎'
    'BSPC': '⌫'
    'BSPC': '⌫'
    'DELETE': '⌦'
    'INSERT': '⎀'
    'LEFT': '←'
    'UP': '↑'
    'RGHT': '→'
    'DOWN': '↓'
    'APP': 'Menu'
    'HOME': '⇤'
    'END': '⇥'
    'PGUP': '⇞'
    'PGDN': '⇟'
    'LSFT': '⇧'
    'RSFT': '⇧'
    'QK_REP': 'Repeat Key'
    'OSM_RSFT': '⇧'
    'OSM_LSFT': '⇧'
    'LCTL': '^'
    'RCTL': '^'
    'CTL_ESC': "Esc ^"
    'CTL_QUOT': "' ^"
    'LALT': '⎇'
    'RALT': '⎇'
    'TAB': '⭾'
    'NAV_V': 'V NAV'
    'WM_M': 'M GUI'
    'NUM_G': 'G NUM'
    'GUI_M': 'M GUI'
    'GUI_P': 'P ⌘'
    'S(KC_QUOT)': ':'
    'LALT_L': 'L ⎇'
    'RSFT_K': 'K ⇧'
    'LCTL_J': 'J ^'
    'GUI_Q': 'Q ⌘'
    'LALT_S': 'S ⎇'
    'LSFT_D': 'D ⇧'
    'LCTL_F': 'F ^'
    'ALT_ENT': "⏎ ⎇"
    'NUM_SPC': 'SPC NUM'
    'ENT': "⏎"
    'ALT_SPC': "Spc ⎇"
    'HYPER': '✧'
    'LGUI': '⌘'
    'SUP_BSLS': "\\ ⌘"
    'SUP_TAB': "⭾ ⌘"
    'RGUI': '⌘'
    'CZ_CARETED': 'ˇ Prefix'
    'CZ_ACUTED': '´ Prefix'
    'SYM_SCLN': "; SYM"
    'SYM_A': "A SYM"
    'QK_LOCK': 'Lock Key'
    'QK_LLCK': 'Lock Layer'
    'DT_UP': 'Term inc'
    'DT_DOWN': 'Term dec'
    'DT_PRNT': 'Term print'
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
