OLED_ENABLE = no
ENCODER_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
CONVERT_TO = liatris

# TAP_DANCE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_LOCK_ENABLE = yes
